src/ClubBundle/Entity/Events.php
<?php

namespace ClubBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use UserBundle\Entity\User;


/**
 * Events
 *
 * @ORM\Table(name="events")
 * @ORM\Entity(repositoryClass="ClubBundle\Repository\EventsRepository")
 */
class Events
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     *
     * @ORM\Column(name="nom", type="string", length=255)
     */
    private $nom;

    /**
     *
     * @ORM\Column(name="description", type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(name="locationLongitude", type="float")
     */
    private $locationLongitude;

    /**
     * @ORM\Column(name="locationLatitude", type="float")
     */
    private $locationLatitude;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_start", type="date")
     */
    private $date_start;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_end", type="date")
     */
    private $date_end;

    /**
     * @var float
     *
     * @ORM\Column(name="prix", type="float")
     */
    private $prix;

    /**
     * @var string
     *
     * @ORM\Column(name="poster", type="string", length=255)
     */
    private $poster;

    /**
     * @Assert\File(maxSize="500k")
     */
    public $file;

    /**
     * @var int
     *
     * @ORM\Column(name="nbreparticipation", type="integer", nullable=true)
     */
    private $nbreparticipation;



    /**
     * @ORM\Column(name="maxPlaces", type="integer")
     * @Assert\Type(type="integer", message="Event's Maximum Places Should Be Valid"),
     * @Assert\Range(min=9, minMessage="Event's Maximum Places Should Be Valid", max=9999, maxMessage="Event's Maximum Places Should Be Valid", invalidMessage="Event's Maximum Places Should Be Valid")
     */
    private $maxPlaces;

    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User")
     * @ORM\JoinColumn(name="user",referencedColumnName="id", onDelete="cascade")
     */
    private $user;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Events
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Events
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }


    public function getLocationLongitude()
    {
        return $this->locationLongitude;
    }


    public function setLocationLongitude($locationLongitude)
    {
        $this->locationLongitude = $locationLongitude;
    }


    public function getLocationLatitude()
    {
        return $this->locationLatitude;
    }

    /**
     * @param mixed $locationLatitude
     */
    public function setLocationLatitude($locationLatitude)
    {
        $this->locationLatitude = $locationLatitude;
    }




    /**
     * @return \DateTime
     */
    public function getDateStart()
    {
        return $this->date_start;
    }

    /**
     * @param \DateTime $date_start
     */
    public function setDateStart($date_start)
    {
        $this->date_start = $date_start;
    }

    /**
     * @return \DateTime
     */
    public function getDateEnd()
    {
        return $this->date_end;
    }

    /**
     * @param \DateTime $date_end
     */
    public function setDateEnd($date_end)
    {
        $this->date_end = $date_end;
    }


    /**
     * Set prix
     *
     * @param float $prix
     *
     * @return Events
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * Get prix
     *
     * @return float
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * Set poster
     *
     * @param string $poster
     *
     * @return Events
     */
    public function setPoster($poster)
    {
        $this->poster = $poster;

        return $this;
    }

    /**
     * Get poster
     *
     * @return string
     */
    public function getPoster()
    {
        return $this->poster;
    }
    public function getWebPath()
    {
        return null === $this->poster ? null : $this->getUploadDir().'/'.$this->poster;
    }
    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../web/'.$this->getUploadDir();
    }
    protected function getUploadDir()
    {
        return 'images';
    }
    public function uploadPoster()
    {
        if (null === $this->file) {
            return;
        }
        if(!$this->id){
            $this->file->move($this->getUploadRootDir(), $this->file->getClientOriginalName());
        }else{

            $this->file->move($this->getUploadRootDir(), $this->file->getClientOriginalName());
        }
        $this->setPoster($this->file->getClientOriginalName());


    }
    public function setMaxPlaces($maxPlaces)
    {
        $this->maxPlaces = $maxPlaces;

        return $this;
    }

    public function getMaxPlaces()
    {
        return $this->maxPlaces;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return int
     */
    public function getNbreparticipation()
    {
        return $this->nbreparticipation;
    }

    /**
     * @param int $nbreparticipation
     */
    public function setNbreparticipation($nbreparticipation)
    {
        $this->nbreparticipation = $nbreparticipation;
    }
    public function removeMember(User $member)
    {
        if ($this->members->contains($member)) {
            $this->members->removeElement($member);
        }

        return $this;
    }

}

src/ClubBundle/Form/EventsType.php
<?php

namespace ClubBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventsType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('nom')
                ->add('description',TextareaType::class)

                ->add('locationLongitude',HiddenType::class)
                ->add('locationLatitude',HiddenType::class)
                ->add('location', MapType::class, [
                'mapped' => false
            ])
                ->add('date_start',DateTimeType::class,[
                    'attr' => ['class' => 'datepicker'],
                ])
                ->add('date_end',DateTimeType::class)
                ->add('prix')
                ->add('file')
                ->add('maxPlaces');

    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ClubBundle\Entity\Events'
        ));
    }


    public function getBlockPrefix()
    {
        return 'clubbundle_events';
    }


}

src/ClubBundle/Controller/EventsController.php
<?php

namespace ClubBundle\Controller;

use ClubBundle\Entity\Events;
use ClubBundle\Form\EventsType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * Event controller.
 *
 */
class EventsController extends Controller
{
    /**
     * Lists all event entities.
     *
     */
    public function indexAction()
    {


        $em = $this->getDoctrine()->getManager();

        $events = $em->getRepository('ClubBundle:Events')->findAll();

        return $this->render('events/index.html.twig', array(
            'events' => $events,
        ));
    }

    /**
     *
     *
     *
     */
    public function newAction(Request $request)
    {
        $event = new Events();
        $form = $this->createForm('ClubBundle\Form\EventsType', $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $event->uploadPoster();
            $em->persist($event);
            $em->flush();

            //return $this->redirectToRoute('events_show', array('id' => $event->getId()));
        }

        return $this->render("@Club/Events/events.html.twig", array(
            'event' => $event,
            'form' => $form->createView(),
        ));
        $this->render("@Club/Events/viewE.html.twig");

    }

    /**
     * Finds and displays a event entity.
     *
     */
    public function showAction()
    {
        $em=$this->getDoctrine()->getManager();
        $events=$em->getRepository("ClubBundle:Events")->findAll();
        return $this->render("ClubBundle:Events:viewE.html.twig",array('events'=>$events));

    }



    public function mapAction()
    {
        return $this->render("@Club/Events/map.html.twig");

    }

    function deleteEventAction($id){
        $em=$this->getDoctrine()->getManager();
        $event=$this->getDoctrine()->getRepository(Events::class)
            ->find($id);
        $em->remove($event);
        $em->flush();
        return $this->redirectToRoute('AfficheLivre');
    }


    public function editAction(Request $request,$id)
    {
        {

            $em = $this->getDoctrine()->getManager();
            $event = $this->getDoctrine()
                ->getRepository(Events::class)
                ->find($id);
            $Form = $this->createForm(EventsType::class, $event);
            $Form->handleRequest($request);

            if ($Form->isSubmitted()) {
                $em->flush();
                return $this->redirectToRoute('AfficheLivre');

            }
            return $this->render("ClubBundle:Events:edit.html.twig",
                array('f' => $Form->createView()));


        }
    }

    /**
     * @Route("/event/{id}", name="events_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Events $event)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($event);
        $em->flush();
        return new Response();
    }


    /**
     * Creates a form to delete a event entity.
     *
     * @param Events $event The event entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Events $event)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('events_delete', array('id' => $event->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/ClubBundle/Resources/views/Events/edit.html.twig
{% extends "ClubBundle::baseE.html.twig" %}

{% block contant %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">


                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12">
                                <!-- jquery validation -->
                                <div class="card card-primary">
                                    <div class="card-header">
                                        <h3 class="card-title">Modifier les champs : </h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <!-- form start -->
                                    {{ form_start(f) }}
                                    <div class="card-body">



                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Nom de l'evenement</label>
                                            {{ form_widget(f.nom ,{'attr':{'class':'form-control','placeholder': '...'}} ) }}
                                        </div>



                                        <div class="form-group">
                                            <label>Description</label>
                                            {{ form_widget(f.description,{'attr':{'class':'form-control','placeholder': '...'}}) }}
                                        </div>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>


                <div class="form-group">
                    <label>localisation</label>
                    {{ form_widget(f.location) }}
                </div>

                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12">
                                <!-- jquery validation -->
                                <div class="card card-primary">

                                    <div class="card-body">

                                        <div class="form-group">
                                            <label>Date début</label>
                                            {{ form_widget(f.date_start) }}
                                        </div>



                                        <div class="form-group">
                                            <label>Date fin</label>
                                            {{ form_widget(f.date_end) }}
                                        </div>



                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12">
                                <!-- jquery validation -->
                                <div class="card card-primary">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>prix</label>
                                            {{ form_widget(f.prix,{'attr':{'class':'form-control','placeholder': '...'}}) }}
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputFile">File input</label>
                                            <div class="input-group">
                                                <div class="custom-file">

                                                    {{ form_widget(f.file,{'attr':{'class':'custom-file-input','id':'exampleInputFile'}}) }}
                                                    <label class="custom-file-label" for="exampleInputFile"></label>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- left column -->
                            <div class="col-md-12">
                                <!-- jquery validation -->
                                <div class="card card-primary">
                                    <div class="card-body">

                                        <div class="form-group">
                                            <label>Max places</label>
                                            {{ form_widget(f.maxPlaces,{'attr':{'class':'form-control','placeholder': '...'}}) }}
                                        </div>

                                        <div class="form-group justify-content-center">

                                            <input type="submit" value="Sauvegarder les modifications" class="btn btn-success " />
                                        </div>

                                        {{ form_end(f) }}

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>




            </div>
        </div>
    </div>
{% endblock %}

src/ClubBundle/Resources/views/Events/viewE.html.twig
{% extends 'Back/Back.html.twig' %}

{% block contant %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h4>Liste des évènements</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Projects</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i></button>

                </div>
            </div>


            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th style="width: 1%">

                        </th>
                        <th style="width: 20%">
                            Nom
                        </th>
                        <th style="width: 30%">
                            Créateur
                        </th>
                        <th>
                            Progression de l'événement
                        </th>
                        <th style="width: 8%" class="text-center">
                            Status
                        </th>
                        <th style="width: 20%">
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}

                        <div class="modal fade" id="modal-default">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Détails</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">


                                        <h1 class="display-4 mb-3">{{ event.nom }}</h1>
                                        <div class="row">

                                            <div class="col-8">
                                                <dl class="row">
                                                    <dt class="col-sm-3">Date :</dt>
                                                    <dd class="col-sm-9">De : {{ event.dateStart|date('Y-m-d') }}.  à :{{ event.dateEnd|date('Y-m-d') }}</dd>
                                                    <dt class="col-sm-3">Prix :</dt>
                                                    <dd class="col-sm-9">{{ event.prix }} DT</dd>
                                                    <dt class="col-sm-3">Location </dt>
                                                    <dd class="col-sm-9" style="height: 20rem; width: 20rem" id='map'></dd>
                                                    <dt class="col-sm-3">Descrip :</dt>
                                                    <dd class="col-sm-9">{{ event.description }}</dd>
                                                </dl>
                                            </div>
                                        </div>



                                        <script src='https://api.mapbox.com/mapbox-gl-js/v1.7.0/mapbox-gl.js'></script>
                                        <script>
                                            var map = new mapboxgl.Map({
                                                accessToken: 'pk.eyJ1Ijoic2FtaW1lc3Nhb3VkaSIsImEiOiJjazZweTJpYjcwY2RkM2xuOWJmcTY4ZGVtIn0.eTDZLW5JBIGHv2YjZDD7zQ',
                                                container: 'map',
                                                style: 'mapbox://styles/mapbox/satellite-streets-v11',
                                                center: [9.9899199, 33.7545921],
                                                zoom: 8
                                            });
                                            var marker = new mapboxgl.Marker();
                                            map.setCenter([{{ event.locationLongitude }}, {{ event.locationLatitude }}]);
                                            marker.setLngLat([{{ event.locationLongitude }}, {{ event.locationLatitude }}]).addTo(map);
                                        </script>





                                    </div>
                                    <div class="modal-footer justify-content-between">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>

                        <tr>
                        <td>

                        </td>
                        <td>
                            <a>
                                {{ event.nom }}
                            </a>
                            <br/>
                            <small>

                            </small>
                        </td>
                        <td>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <img alt="Avatar" class="table-avatar" src="{{ asset('bundles/dist/img/avatar5.png')}}">
                                </li>

                            </ul>
                        </td>
                        <td class="project_progress align-bottom">
                            <div class="progress progress-sm">
                                <div class="progress-bar {{ event.nbreparticipation == event.maxPlaces ? "bg-red" : "bg-green" }}" role="progressbar" aria-volumenow="0" aria-volumemin="0" aria-volumemax="100" style="width: calc( ({{ event.nbreparticipation / event.maxPlaces }}) * 100%)">
                                </div>
                            </div>
                            <small>
                                {{ event.nbreparticipation / event.maxPlaces *100 }} % Complet
                            </small>
                        </td>
                        <td class="project-state">
                            <span class="badge {{ event.nbreparticipation == event.maxPlaces ? "badge-warning" : "badge-success" }}">{{ event.nbreparticipation == event.maxPlaces ? "Complet !" : "Incomplet" }}</span>
                        </td>
                        <td class="project-actions text-right">
                            <a class="btn btn-primary btn-sm" href="#" data-toggle="modal" data-target="#modal-default ">
                                <i class="fas fa-eye">
                                </i>

                            </a>
                            <a class="btn btn-info btn-sm" href="{{ path('events_edit',{'id':event.id}) }}">
                                <i class="fas fa-pencil-alt">
                                </i>

                            </a>
                            <a class="btn btn-danger btn-sm" onclick="fetch('{{ path('events_delete', { 'id': event.id }) }}', { method: 'DELETE' }).then((res) => {this.parentNode.parentNode.remove()})">
                                <i class="fas fa-trash">
                                </i>

                            </a>
                        </td>
                    </tr>






            {% endfor %}








                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->



{% endblock %}